""""Data lineage" view of an IS package: which columns of the source tables feed which columns of the target
tables, published documents or files, and by which rule (SELECT DISTINCT, join to look up a key, formatted date,
quantity × price, API response, constant, choice depending on a condition). The lineage is computed by
interpreting the deployed flows symbolically (MAP copies, MAPSET, built-in services, SELECT / INSERT / BatchInsert
adapters, publication, file writing) and the SQL of the adapter services; the table columns come from the
db/*.sql scripts. Rendering: SVG board (sources → transformations → targets, hover = lineage of a column) and a
narrative per target table. Embedded in flows.html by wm/flowdoc.py.
"""
import html, re
from flowgraph import mapset_value
from flowexec import short

T = {
    "fr": {"title_etl": "Du staging au schéma en étoile : cheminement des données", "title": "Cheminement des données : des sources aux cibles",
           "hint": "Chaque colonne cible indique la règle qui la calcule ; survoler une colonne (ou une transformation) éclaire son lignage. "
                   "Calculé à partir des flows déployés, du SQL des services adaptateur et des scripts de création des tables.",
           "distinct": "une ligne par valeur distincte de", "reads": "lit", "batches": "par lots", "join": "jointure", "joins": "jointures sur",
           "to_find_keys": "pour retrouver les clés techniques", "writes": "insère dans", "tx": "dans une transaction (rollback en cas d'erreur)",
           "per_row": "pour chaque ligne", "per_value": "pour chaque valeur", "computed": "champs calculés dans le flow", "db_gen": "généré par la base",
           "default": "valeur par défaut", "not_fed": "non alimenté", "format": "au format", "locale": "langue", "if": "si", "else": "sinon",
           "in": "dans", "api": "réponse de l'API", "const": "constante", "key_of": "clé de", "via": "via", "source": "source", "target": "cible",
           "step": "Étape", "how": "Comment on y arrive, table par table", "cols": "colonnes", "legend": "Légende", "k_src": "table ou flux source",
           "k_card": "transformation (flow service)", "k_tgt": "table, document ou fichier cible", "k_line": "lignage d'une colonne (survol)",
           "publish": "publie le document", "file": "écrit le fichier", "then": "puis", "and": "et", "receives": "reçoit", "notif": "notification JDBC",
           "sum": "somme", "weekend_rule": "true si {sw} ∈ {{{vals}}}, sinon false", "choice": "selon", "calls": "appelle l'API"},
    "en": {"title_etl": "From staging to the star schema: how the data flows", "title": "Data lineage: from sources to targets",
           "hint": "Each target column shows the rule that computes it; hover a column (or a transformation) to light up its lineage. "
                   "Computed from the deployed flows, the adapter services' SQL and the table creation scripts.",
           "distinct": "one row per distinct value of", "reads": "reads", "batches": "in batches", "join": "join", "joins": "joins on",
           "to_find_keys": "to look up the surrogate keys", "writes": "inserts into", "tx": "in one transaction (rollback on error)",
           "per_row": "for each row", "per_value": "for each value", "computed": "fields computed in the flow", "db_gen": "generated by the database",
           "default": "default value", "not_fed": "not fed", "format": "formatted as", "locale": "locale", "if": "if", "else": "else",
           "in": "in", "api": "API response", "const": "constant", "key_of": "key of", "via": "via", "source": "source", "target": "target",
           "step": "Step", "how": "How it gets there, table by table", "cols": "columns", "legend": "Legend", "k_src": "source table or feed",
           "k_card": "transformation (flow service)", "k_tgt": "target table, document or file", "k_line": "column lineage (hover)",
           "publish": "publishes the document", "file": "writes the file", "then": "then", "and": "and", "receives": "receives", "notif": "JDBC notification",
           "sum": "sum", "weekend_rule": "true if {sw} ∈ {{{vals}}}, else false", "choice": "depending on", "calls": "calls the API"},
}
PALETTE = ["#4589ff", "#42be65", "#a56eff", "#f1c21b", "#33b1ff", "#ff7eb6", "#08bdba", "#ff832b"]
EXCLUDE = re.compile(r"(^|[._])(log|logs|journal|control|audit)($|[._])", re.I)      # technical tables (log, control) left out of the lineage


# ------------------------------------------------------------------ table schema (db/*.sql)
def parse_schema(paths):
    """CREATE TABLE schema.table ( col type ... [-- commentaire] ) -> {table: [(col, type, note, generated)]}"""
    tables = {}
    for path in paths:
        try:
            sql = open(path, encoding="utf-8").read()
        except OSError:
            continue
        for m in re.finditer(r"CREATE TABLE(?: IF NOT EXISTS)?\s+([\w.]+)\s*\((.*?)\n\);", sql, re.S):
            name, body = m.group(1), m.group(2)
            cols = []
            for line in body.split("\n"):
                raw, _, note = line.partition("--")
                raw = raw.strip().rstrip(",")
                if not raw or raw.upper().startswith(("PRIMARY", "UNIQUE", "CONSTRAINT", "FOREIGN", "CHECK")):
                    continue
                parts = raw.split()
                col, ctype = parts[0], " ".join(parts[1:2])
                up = raw.upper()
                gen = "serial" if "SERIAL" in up else ("default" if "DEFAULT" in up else "")
                cols.append((col, ctype, note.strip(), gen))
            tables[name] = cols
    return tables


# ------------------------------------------------------------------ SQL of the adapter services
def split_top(s, sep=","):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "(": depth += 1
        elif ch == ")": depth -= 1
        if ch == sep and depth == 0:
            out.append(cur); cur = ""
        else:
            cur += ch
    if cur.strip(): out.append(cur)
    return [x.strip() for x in out]


def parse_select(sql):
    s = " ".join(sql.split())
    m = re.match(r"(?:WITH .*?\)\s*)?SELECT\s+(DISTINCT\s+)?(.*?)\s+FROM\s+(.*)$", s, re.I | re.S)
    if not m:
        return None
    distinct, sel, rest = bool(m.group(1)), m.group(2), m.group(3)
    where = ""
    mw = re.search(r"\sWHERE\s+(.*?)(?:\sORDER BY|\sGROUP BY|\sLIMIT|$)", " " + rest, re.I)
    if mw: where = mw.group(1).strip()
    from_part = re.split(r"\sWHERE\s|\sORDER BY\s|\sGROUP BY\s|\sLIMIT\s", " " + rest, 1, re.I)[0].strip()
    tables, joins = {}, []
    for i, seg in enumerate(re.split(r"\s+(?:LEFT\s+|INNER\s+)?JOIN\s+", from_part, flags=re.I)):
        seg = seg.strip()
        mt = re.match(r"([\w.]+)(?:\s+(?:AS\s+)?(\w+))?(?:\s+ON\s+(.*))?$", seg, re.I)
        if not mt: continue
        tbl, alias, on = mt.group(1), mt.group(2), mt.group(3)
        if alias and alias.upper() in ("ON", "USING"): alias = None
        tables[alias or tbl] = tbl
        if on: joins.append((alias or tbl, tbl, on.strip()))
    cols = []
    for item in split_top(sel):
        ma = re.match(r"(.*?)\s+AS\s+(\w+)$", item, re.I)
        expr, alias = (ma.group(1), ma.group(2)) if ma else (item, None)
        mc = re.match(r"^(?:(\w+)\.)?(\w+)$", expr)
        if mc:
            cols.append({"name": alias or mc.group(2), "expr": expr, "table": tables.get(mc.group(1), tables.get(mc.group(1) or "", None)) if mc.group(1) else (next(iter(tables.values())) if len(tables) == 1 else None), "col": mc.group(2), "fn": None})
        else:
            refs = [(tables.get(a) or a, c) for a, c in re.findall(r"\b(\w+)\.(\w+)\b", expr) if a not in ("to_char",)]
            if not refs:
                refs = [(next(iter(tables.values())) if len(tables) == 1 else None, c) for c in re.findall(r"\b([a-z_]+)\b", expr) if c.lower() not in ("to_char", "count", "sum", "max", "min", "avg", "round", "extract", "coalesce", "as", "from", "epoch", "select", "date", "text")][:1]
            cols.append({"name": alias or expr, "expr": expr, "table": refs[0][0] if refs else None, "col": refs[0][1] if refs else None, "fn": expr})
    return {"distinct": distinct, "cols": cols, "tables": tables, "joins": joins, "where": where}


def parse_insert(sql):
    m = re.match(r"\s*INSERT\s+INTO\s+([\w.]+)\s*\((.*?)\)\s*VALUES", " ".join(sql.split()), re.I | re.S)
    if not m: return None
    return m.group(1), [c.strip() for c in m.group(2).split(",")]


# ------------------------------------------------------------------ expressions symboliques
def E(kind, **kw):
    d = {"kind": kind}; d.update(kw); return d


def norm(path):
    segs = []
    for seg in path.strip("/").split("/"):
        seg = re.sub(r"\[\d*\]", "", seg.split(";")[0])
        if seg: segs.append(seg)
    return "/".join(segs)


class Interp:
    def __init__(self, ctx, svc):
        self.ctx, self.svc, self.env = ctx, svc, {}
        self.writes, self.reads, self.notes = [], [], {"tx": False, "loops": [], "extract": [], "inputs": [], "api": []}
        self.file_header = None

    def resolve(self, key):
        if key in self.env:
            v = self.env[key]
            if "/" in key and v["kind"] in ("col", "fn", "sqlfn", "lookup", "tpl", "choice", "const"):
                return E("field", name=key.split("/")[-1], expr=v)
            return v
        parts = key.split("/")
        for i in range(len(parts) - 1, 0, -1):
            base, rest = "/".join(parts[:i]), "/".join(parts[i:])
            b = self.env.get(base)
            if b is None: continue
            if b["kind"] == "list": return b["cols"].get(rest, E("var", name=key))
            if b["kind"] == "docref": return E("col", table=b["table"], col=rest.replace("/", "."))
            if b["kind"] == "prefix":
                v = self.env.get(b["base"] + "/" + rest)
                if v is not None: return v
        return E("var", name=key)

    def prefix_cols(self, base):
        """fields written under base/… (document built field by field)"""
        out = {}
        for k, v in self.env.items():
            if k.startswith(base + "/"):
                out[k[len(base) + 1:].replace("/", ".")] = v
        return out

    def list_cols(self, expr, base_key):
        if expr and expr["kind"] == "list": return dict(expr["cols"])
        return self.prefix_cols(base_key) if base_key else {}

    def apply_map(self, nodes, target=None):
        """MAPCOPY / MAPSET into env (target=None) or into an argument dictionary"""
        dst = self.env if target is None else target
        for n in nodes:
            t = n.get("type")
            if t == "MAPCOPY":
                key, src = norm(n.get("to", "")), norm(n.get("from", ""))
                dst[key] = self.resolve(src)
                if target is not None and src in self.env and self.env[src]["kind"] == "prefix":
                    pass
                if target is not None:
                    dst["__src__" + key] = src
            elif t == "MAPSET":
                key, val = norm(n.get("field", "")), mapset_value(n)
                if n.get("overwrite") == "false" and key in dst: continue
                if n.get("variables") == "true" and "%" in val:
                    parts, refs = re.split(r"%([^%]+)%", val), []
                    tpl = []
                    for i, p in enumerate(parts):
                        tpl.append(("lit", p) if i % 2 == 0 else ("ref", self.resolve(norm(p))))
                    dst[key] = E("tpl", parts=tpl, raw=val)
                else:
                    dst[key] = E("const", value=val)

    def walk(self, nodes):
        for n in nodes:
            t = n.get("type")
            if t == "INVOKE": self.invoke(n)
            elif t == "MAP": self.apply_map(n.get("nodes", []))
            elif t == "SEQUENCE": self.walk(n.get("nodes", []))
            elif t in ("LOOP", "REPEAT"):
                arr = norm(n.get("in-array", ""))
                if arr: self.notes["loops"].append(arr)
                self.walk(n.get("nodes", []))
            elif t == "BRANCH":
                before = dict(self.env); assigned = {}
                for c in n.get("nodes", []):
                    self.env = dict(before)
                    self.walk(c.get("nodes", []) if c.get("type") == "SEQUENCE" else [c])
                    lab = str(c.get("label", "")) if c.get("type") == "SEQUENCE" else ""
                    for k, v in self.env.items():
                        if before.get(k) is not v:
                            assigned.setdefault(k, []).append((lab, v))
                self.env = before
                for k, cases in assigned.items():
                    self.env[k] = E("choice", switch=norm(n.get("switch", "")), cases=cases)

    def invoke(self, n):
        name = n["service"]
        maps = n.get("nodes", [])
        inp = [x for m in maps if m.get("mode") == "INPUT" for x in m.get("nodes", [])]
        out = [x for m in maps if m.get("mode") == "OUTPUT" for x in m.get("nodes", [])]
        args = {}
        self.apply_map(inp, args)
        sname = short(name)
        ctx = self.ctx
        if name in ctx.select_sql:
            p = parse_select(ctx.select_sql[name])
            cols = {}
            if p:
                for c in p["cols"]:
                    if c["fn"]:
                        cols[c["name"]] = E("sqlfn", expr=c["fn"], table=c["table"], col=c["col"])
                    else:
                        tbl = c["table"]
                        joined = next((j for j in p["joins"] if j[1] == tbl), None)
                        if joined and tbl != next(iter(p["tables"].values())):
                            cols[c["name"]] = E("lookup", table=tbl, col=c["col"], on=joined[2])
                        else:
                            cols[c["name"]] = E("col", table=tbl, col=c["col"])
                self.notes["extract"].append({"service": name, "sql": p, "cols": list(cols)})
                for tbl in p["tables"].values(): self.reads.append(tbl)
            self.env[f"{sname}Output/results"] = E("list", cols=cols, service=name)
        elif name in ctx.batch_insert:
            table, exclude = ctx.batch_insert[name]
            src_key = args.get("__src__" + f"{sname}Input/inputs", "")
            cols = self.list_cols(args.get(f"{sname}Input/inputs"), src_key)
            for col, ctype, note, gen in ctx.schema.get(table, []):
                if col in exclude: continue
                self.writes.append({"target": table, "col": col, "expr": cols.get(col), "service": self.svc, "adapter": name})
            self.notes["write"] = (table, name, "BatchInsert")
        elif name in ctx.insert_sql:
            table, cols = ctx.insert_sql[name]
            for col in cols:
                self.writes.append({"target": table, "col": col, "expr": args.get(f"{sname}Input/{col}"), "service": self.svc, "adapter": name})
            self.notes["write"] = (table, name, "INSERT")
        elif name.startswith("pub.publish:publish"):
            doc = args.get("documentTypeName", {}).get("value", "?")
            src_key = args.get("__src__document", "")
            cols = self.list_cols(args.get("document"), src_key)
            for col, ex in cols.items():
                self.writes.append({"target": "⟨" + short(doc) + "⟩", "col": col, "expr": ex, "service": self.svc, "adapter": name, "doc": doc})
            self.notes["write"] = ("⟨" + short(doc) + "⟩", name, "publish")
        elif name.startswith("pub.file:") and sname in ("stringToFile", "bytesToFile"):
            data = args.get("data")
            fname = args.get("fileName")
            fn = ctx.file_label(fname, self.env)
            if data and data["kind"] == "const" and ";" in data["value"]:
                self.file_header = [c.strip() for c in data["value"].strip().split(";")]
            elif data and data["kind"] == "tpl":
                parts = [p for p in data["parts"]]
                # split the template on ';': each field = one reference
                fields, cur = [], []
                for kind, v in parts:
                    if kind == "lit":
                        pieces = v.split(";")
                        cur.append(pieces[0])
                        for extra in pieces[1:]:
                            fields.append(cur); cur = [extra]
                    else:
                        cur.append(v)
                fields.append(cur)
                header = self.file_header or [f"col{i + 1}" for i in range(len(fields))]
                for i, f in enumerate(fields):
                    refs = [x for x in f if isinstance(x, dict)]
                    ex = refs[0] if len(refs) == 1 else E("tpl", parts=[("ref", x) if isinstance(x, dict) else ("lit", x) for x in f], raw="")
                    if i < len(header):
                        self.writes.append({"target": fn, "col": header[i], "expr": ex, "service": self.svc, "adapter": name})
                self.notes["write"] = (fn, name, "file")
        elif name.startswith("pub.art.transaction:start"):
            self.notes["tx"] = True
        elif not name.startswith(("pub.", "wm.")) and name not in ctx.flows:
            path = args.get("path", {}).get("raw") or args.get("path", {}).get("value", "")
            label = ctx.t["api"] + " · " + (args.get("method", {}).get("value", "GET").upper() + " " + re.sub(r"%[^%]+%", "{…}", path)).strip()
            self.notes["api"].append(label)
            for x in out:
                if x.get("type") == "MAPCOPY":
                    self.env[norm(x["to"])] = E("docref", table=label)
            return
        elif name in ctx.flows:
            pass
        else:
            for x in out:
                if x.get("type") == "MAPCOPY":
                    src, dst = norm(x["from"]), norm(x["to"])
                    if "/" not in src:
                        self.env[src] = E("fn", name=name, args={k: v for k, v in args.items() if not k.startswith("__src__")})
        for x in out:
            if x.get("type") == "MAPCOPY":
                self.env[norm(x["to"])] = self.resolve(norm(x["from"]))
            elif x.get("type") == "MAPSET":
                self.apply_map([x])


class Ctx:
    def __init__(self, flows, custom_sql, batch_insert, schema, notifications, lang, file_names):
        self.flows, self.schema, self.t = flows, schema, T[lang]
        self.select_sql = {n: sql for n, sql in custom_sql.items() if sql.lstrip().upper().startswith(("SELECT", "WITH"))}
        self.insert_sql = {}
        for n, sql in custom_sql.items():
            p = parse_insert(sql)
            if p: self.insert_sql[n] = p
        self.batch_insert = batch_insert
        self.notif_tables = {doc: origin for _, doc, origin, *_ in notifications}
        self.file_names = file_names

    def file_label(self, fname, env):
        if fname and fname["kind"] == "tpl":
            raw = fname["raw"]
        elif fname and fname["kind"] == "const":
            raw = fname["value"]
        else:
            raw = self.file_names.get("default", "fichier")
        return "📄 " + raw.rsplit("/", 1)[-1].replace("%day%", "<day>" if self.t is T["en"] else "<jour>")


# ------------------------------------------------------------------ readable expressions
def readable(ex, t, main_table=None):
    if ex is None: return ""
    k = ex["kind"]
    if k == "col":
        if ex["table"] in (main_table, None): return ex["col"]
        return f"{ex['col']} (API)" if str(ex["table"]).startswith(t["api"]) else f"{ex['col']} ({ex['table']})"
    if k == "const":
        v = ex["value"]
        return v if re.match(r"^-?\d+(\.\d+)?$", v) or v in ("true", "false") else f"'{v}'"
    if k == "field": return ex["name"]
    if k == "var": return "?" + ex["name"].split("/")[-1]
    if k == "lookup":
        on = re.sub(r"\b\w+\.", "", ex["on"])
        left = on.split("=")[0].strip()
        return f"{t['key_of']} {ex['table'].split('.')[-1]} ({t['join']} {left})"
    if k == "sqlfn":
        m = re.match(r"to_char\((\w+\.)?(\w+),\s*'([^']+)'\)", ex["expr"], re.I)
        if m: return f"{m.group(2)} {t['format']} {m.group(3)}"
        return ex["expr"]
    if k == "tpl":
        return "".join(p if kind == "lit" else (p["value"] if p["kind"] == "const" else "⟨" + readable(p, t, main_table) + "⟩") for kind, p in ex["parts"])
    if k == "choice":
        sw = ex["switch"].split("/")[-1]
        vals = [(lab, readable(v, t, main_table)) for lab, v in ex["cases"]]
        by_val = {}
        for lab, v in vals: by_val.setdefault(v, []).append(lab)
        if len(vals) == 1:
            return f"{vals[0][1]} {t['if']} {sw} = {vals[0][0]}"
        if len(by_val) == 2 and any("$default" in labs for labs in by_val.values()):
            other = next(v for v, labs in by_val.items() if "$default" not in labs)
            dflt = next(v for v, labs in by_val.items() if "$default" in labs)
            return f"{other} {t['if']} {sw} ∈ {{{', '.join(by_val[other])}}}, {t['else']} {dflt}"
        return f"{t['choice']} {sw} : " + ", ".join(f"{lab} → {v}" for lab, v in vals)
    if k == "fn":
        name, a = short(ex["name"]), ex["args"]
        r = lambda key: readable(a.get(key), t, main_table)
        if name == "dateTimeFormat":
            pat = a.get("newPattern")
            pats = readable(pat, t, main_table).strip("'") if pat else "?"
            loc = f", {t['locale']} {r('locale')}" if a.get("locale") else ""
            return f"{r('inString')} {t['format']} {pats}{loc}"
        if name == "multiplyFloats": return f"{r('num1')} × {r('num2')}"
        if name == "addInts": return f"{r('num1')} + {r('num2')}"
        if name == "divideInts": return f"({r('num1')}) ÷ {r('num2')}"
        if name == "divideFloats": return f"{r('num1')} ÷ {r('num2')}"
        if name == "generateUUID": return "UUID"
        if name in ("getCurrentDateString", "currentNanoTime"): return "horodatage" if t is T["fr"] else "timestamp"
        if name == "concat": return f"{r('inString1')} + {r('inString2')}"
        return name + "(" + ", ".join(f"{k}={readable(v, t, main_table)}" for k, v in a.items() if not k.startswith("__src__")) + ")"
    if k == "list": return "…"
    if k == "docref": return ex["table"]
    return "?"


def refs_of(ex, acc=None):
    """(table, column) references of an expression"""
    acc = [] if acc is None else acc
    if not ex: return acc
    k = ex["kind"]
    if k in ("col", "lookup", "sqlfn") and ex.get("table") and ex.get("col"):
        acc.append((ex["table"], ex["col"]))
    elif k == "tpl":
        for kind, p in ex["parts"]:
            if kind == "ref": refs_of(p, acc)
    elif k == "choice":
        for _, v in ex["cases"]: refs_of(v, acc)
    elif k == "fn":
        for kk, v in ex["args"].items():
            if not kk.startswith("__src__"): refs_of(v, acc)
    elif k == "field":
        refs_of(ex["expr"], acc)
    return acc


# ------------------------------------------------------------------ board construction
def analyze(services, custom_sql, batch_insert, schema, notifications, lang, order=None, file_names=None):
    t = T[lang]
    flows = {s["node_nsName"]: s for s in services}
    ctx = Ctx(flows, custom_sql, batch_insert, schema, notifications, lang, file_names or {})
    results = {}
    for name, s in flows.items():
        it = Interp(ctx, name)
        for f in s["svc_sig"].get("sig_in", {}).get("rec_fields", []):
            if f.get("rec_ref"):
                doc = f["rec_ref"]
                it.env[doc] = E("docref", table=ctx.notif_tables.get(doc, "⟨" + short(doc) + "⟩"))
                it.notes["inputs"].append(it.env[doc]["table"])
        try:
            it.walk(s["flow"]["nodes"])
        except Exception as e:      # never blocking: the view stays partial
            it.notes["error"] = str(e)
        it.writes = [w for w in it.writes if not EXCLUDE.search(w["target"])]
        if it.writes:
            results[name] = it
    # nœuds
    nodes = {}   # id -> {"label", "kind", "cols": [...], "rules": {col: (text, refs)}}
    def node(nid, kind):
        if nid not in nodes:
            nodes[nid] = {"id": nid, "label": nid, "kind": kind, "cols": [], "rules": {}, "gen": {}}
        return nodes[nid]
    cards = []
    order = order or list(results)
    for name in [n for n in order if n in results] + [n for n in results if n not in (order or [])]:
        it = results[name]
        targets = {}
        for w in it.writes:
            targets.setdefault(w["target"], []).append(w)
        for target, ws in targets.items():
            kind = "doc" if target.startswith("⟨") else ("file" if target.startswith("📄") else "table")
            tn = node(target, kind)
            counts = {}
            for w in ws:
                for tbl, _ in refs_of(w["expr"]): counts[tbl] = counts.get(tbl, 0) + 1
            main = max(counts, key=counts.get) if counts else None
            srcs = set()
            for w in ws:
                if w["col"] not in tn["cols"]: tn["cols"].append(w["col"])
                rr = refs_of(w["expr"])
                tn["rules"][w["col"]] = (readable(w["expr"], t, main) if w["expr"] else "", rr, name)
                for tbl, col in rr:
                    srcs.add(tbl)
                    sn = node(tbl, "table" if not (tbl.startswith("⟨") or tbl.startswith(t["api"])) else ("doc" if tbl.startswith("⟨") else "api"))
                    if col not in sn["cols"]: sn["cols"].append(col)
            for col, ctype, note, gen in schema.get(target, []):
                if col not in tn["cols"]:
                    tn["cols"].append(col); tn["gen"][col] = gen or "default"
            cards.append({"id": f"card{len(cards)}", "service": name, "target": target, "sources": sorted(srcs), "notes": it.notes,
                          "desc": flows[name].get("node_comment", ""), "color": PALETTE[len(cards) % len(PALETTE)]})
    # full column list of the source tables known from the schema
    for nid, n in nodes.items():
        if n["kind"] == "table" and nid in schema and not any(c["target"] == nid for c in cards):
            n["cols"] = [c[0] for c in schema[nid]]
            n["src"] = True
    # profondeurs
    depth = {nid: 0 for nid in nodes}
    for _ in range(6):
        for c in cards:
            c["depth"] = 1 + max([depth[s] for s in c["sources"] if s in depth] or [0])
            depth[c["target"]] = max(depth[c["target"]], c["depth"] + 1)
    for nid in nodes: nodes[nid]["depth"] = depth[nid]
    return nodes, cards, t


def card_lines(card, nodes, t, schema):
    """readable summary of a transformation"""
    lines, n = [], card["notes"]
    for tbl in n.get("inputs", []):
        lines.append(f"{t['receives']} {tbl}")
    for ex in n["extract"]:
        p, tbls = ex["sql"], list(ex["sql"]["tables"].values())
        main = tbls[0] if tbls else "?"
        if p["distinct"]:
            lines.append(f"{t['reads']} {main} : {t['distinct']} ({', '.join(c['name'] for c in p['cols'])})")
        else:
            lines.append(f"{t['reads']} {main}" + (f" {t['batches']} ({p['where'].replace('?', '…')})" if "?" in p["where"] else ""))
        if p["joins"]:
            lines.append(f"{t['joins']} {', '.join(j[1].split('.')[-1] for j in p['joins'])} {t['to_find_keys']}")
    for api in n.get("api", []):
        lines.append(f"{t['calls']} {api.split(' · ', 1)[-1]}")
    computed = [c for c, (txt, refs, _) in nodes[card["target"]]["rules"].items() if txt and any(k in txt for k in ("×", "+", "÷", t["format"], "⟨", "∈", "UUID"))]
    if n["loops"]:
        lines.append(f"{t['per_row']} : {len(computed)} {t['computed']}")
    w = n.get("write")
    if w:
        verb = {"BatchInsert": t["writes"], "INSERT": t["writes"], "publish": t["publish"], "file": t["file"]}[w[2]]
        lines.append(f"{verb} {w[0]}" + (f" ({short(w[1])}, {w[2]})" if w[2] in ("BatchInsert",) else f" ({short(w[1])})" if w[2] == "INSERT" else ""))
    if n["tx"]:
        lines.append(t["tx"])
    gen = [c for c, g in nodes[card["target"]]["gen"].items()]
    if gen:
        lines.append(", ".join(gen) + " : " + t["db_gen"])
    return lines


def esc(s): return html.escape(str(s))


def render(services, custom_sql, batch_insert, schema_files, notifications=(), lang="fr", order=None, title_key="title", file_names=None, sections=None, tr=None):
    tr = tr or (lambda x: x)
    schema = parse_schema(schema_files)
    nodes, cards, t = analyze(services, custom_sql, batch_insert, schema, notifications, lang, order, file_names)
    sections = set(sections or [])
    if not cards:
        return "", ""
    NW, CW, GX, RH, HH, PAD = 300, 330, 70, 17, 26, 20
    cols_x = {}
    maxd = max([n["depth"] for n in nodes.values()] + [c["depth"] for c in cards])
    x = PAD
    for d in range(maxd + 1):
        cols_x[d] = x
        x += (CW if any(c["depth"] == d for c in cards) else NW) + GX
    width = x - GX + PAD
    # column heights
    def node_h(n): return HH + RH * len(n["cols"]) + 6
    card_lines_cache = {c["id"]: card_lines(c, nodes, t, schema) for c in cards}
    def card_h(c): return 30 + 14 * (1 + len(card_lines_cache[c["id"]])) + 8
    ys = {}
    col_items = {}
    for nid, n in nodes.items(): col_items.setdefault(n["depth"], []).append(("n", nid))
    for c in cards: col_items.setdefault(c["depth"], []).append(("c", c["id"]))
    height = 0
    for d, items in col_items.items():
        y = PAD
        for kind, i in items:
            h = node_h(nodes[i]) if kind == "n" else card_h(next(c for c in cards if c["id"] == i))
            ys[i] = (y, h); y += h + 22
        height = max(height, y)
    # vertical centering per column
    for d, items in col_items.items():
        used = sum(ys[i][1] for _, i in items) + 22 * (len(items) - 1)
        off = (height - PAD - used) / 2
        for _, i in items: ys[i] = (ys[i][0] + off, ys[i][1])
    out = [f'<svg class="lg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.0f} {height + 36:.0f}" width="{width:.0f}" height="{height + 36:.0f}" data-w="{width:.0f}">',
           '<style>.lg text{font-family:"IBM Plex Sans","Segoe UI",system-ui,sans-serif}.lg .ln{fill:none;stroke-width:1.4;opacity:.45}.lg .ln.hi{opacity:1;stroke-width:2.6}.lg .ln.dim{opacity:.06}'
           '.lg .row:hover rect{fill:rgba(51,177,255,.15)}.lg .row.hi rect{fill:rgba(51,177,255,.22)}.lg .rule{font-size:9.6px;fill:#8b98a8}.lg .cn{font-size:11px;fill:#e6edf3}.lg .cn.gen{fill:#5b6f8a;font-style:italic}</style>']
    row_pos = {}
    # nœuds
    for nid, n in nodes.items():
        x0, (y0, h) = cols_x[n["depth"]], ys[nid]
        stroke = {"table": "#42be65", "doc": "#a56eff", "file": "#08bdba", "api": "#ff7eb6"}[n["kind"]]
        if n.get("src"): stroke = "#33b1ff"
        out.append(f'<rect x="{x0}" y="{y0:.1f}" width="{NW}" height="{h}" rx="8" fill="#1c2430" stroke="{stroke}" stroke-width="1.5"/>')
        out.append(f'<text x="{x0 + 10}" y="{y0 + 17:.1f}" font-size="12.5" font-weight="700" fill="#e6edf3">{esc(n["label"])}</text>')
        for i, col in enumerate(n["cols"]):
            ry = y0 + HH + i * RH
            rid = f"{nid}.{col}"
            row_pos[rid] = (x0, ry + RH / 2, NW)
            rule = n["rules"].get(col)
            gen = n["gen"].get(col)
            txt = rule[0] if rule else (t["db_gen"] if gen == "serial" else (t["default"] if gen == "default" else ""))
            srcs = ",".join(f"{a}.{b}" for a, b in rule[1]) if rule else ""
            room = max(6, int((NW - 24 - len(col) * 6.6) / 5.4))
            txt = txt if len(txt) <= room else txt[: room - 1] + "…"
            out.append(f'<g class="row" data-id="{esc(rid)}" data-src="{esc(srcs)}"><title>{esc(col)}{(" ← " + rule[0]) if rule and rule[0] else ""}</title>'
                       f'<rect x="{x0 + 1}" y="{ry:.1f}" width="{NW - 2}" height="{RH}" fill="transparent"/>'
                       f'<text class="cn{" gen" if gen and not rule else ""}" x="{x0 + 10}" y="{ry + 12.5:.1f}">{esc(col)}</text>'
                       f'<text class="rule" x="{x0 + NW - 8}" y="{ry + 12.5:.1f}" text-anchor="end">{esc(txt)}</text></g>')
    # cards
    for c in cards:
        x0, (y0, h) = cols_x[c["depth"]], ys[c["id"]]
        href = f"#{c['service']}" if c["service"] in sections else None
        lines = card_lines_cache[c["id"]]
        g = (f'<g class="card" data-card="{c["id"]}"><title>{esc(c["desc"])}</title>'
             f'<rect x="{x0}" y="{y0:.1f}" width="{CW}" height="{h}" rx="10" fill="#161c24" stroke="{c["color"]}" stroke-width="1.6"/>'
             f'<text x="{x0 + 12}" y="{y0 + 18:.1f}" font-size="12.5" font-weight="700" fill="{c["color"]}">{esc(short(c["service"]))}</text>'
             f'<text x="{x0 + CW - 10}" y="{y0 + 18:.1f}" font-size="10" fill="#8b98a8" text-anchor="end">{esc(c["service"].split(":")[0])}</text>')
        for i, ln in enumerate(lines):
            g += f'<text x="{x0 + 12}" y="{y0 + 36 + i * 14:.1f}" font-size="10.5" fill="#c9d1d9">{esc(ln[:62] + ("…" if len(ln) > 62 else ""))}</text>'
        g += "</g>"
        out.append(f'<a href="{href}">{g}</a>' if href else g)
        # lines source -> card -> target
        tgt = nodes[c["target"]]
        for col in tgt["cols"]:
            rule = tgt["rules"].get(col)
            if not rule or rule[2] != c["service"]: continue
            tx, ty, _ = row_pos[f"{c['target']}.{col}"]
            cy = y0 + h / 2
            out.append(f'<path class="ln" data-card="{c["id"]}" data-t="{esc(c["target"] + "." + col)}" data-s="" d="M {x0 + CW} {cy:.1f} C {x0 + CW + GX / 2} {cy:.1f}, {tx - GX / 2} {ty:.1f}, {tx} {ty:.1f}" stroke="{c["color"]}"/>')
            for tbl, scol in rule[1]:
                sid = f"{tbl}.{scol}"
                if sid not in row_pos: continue
                sx, sy, sw = row_pos[sid]
                out.append(f'<path class="ln" data-card="{c["id"]}" data-t="{esc(c["target"] + "." + col)}" data-s="{esc(sid)}" d="M {sx + sw} {sy:.1f} C {sx + sw + GX / 2} {sy:.1f}, {x0 - GX / 2} {cy:.1f}, {x0} {cy:.1f}" stroke="{c["color"]}"/>')
    # legend
    ly = height + 6
    lx = PAD
    for color, lab in (("#33b1ff", t["k_src"]), ("#f1c21b", t["k_card"]), ("#42be65", t["k_tgt"])):
        out.append(f'<rect x="{lx}" y="{ly}" width="14" height="11" rx="3" fill="none" stroke="{color}"/><text x="{lx + 20}" y="{ly + 10}" font-size="11" fill="#8b98a8">{esc(lab)}</text>')
        lx += 20 + len(lab) * 6.4 + 24
    out.append(f'<text x="{lx}" y="{ly + 10}" font-size="11" fill="#8b98a8">— {esc(t["k_line"])}</text>')
    out.append("</svg>")
    # narrative
    story = [f'<h3 class="lgh">{esc(t["how"])}</h3><ol class="lgs">']
    for i, c in enumerate(cards):
        tgt = nodes[c["target"]]
        rules = [(col, r[0]) for col, r in tgt["rules"].items() if r[2] == c["service"] and r[0]]
        story.append(f'<li><b style="color:{c["color"]}">{esc(c["target"])}</b> ← <span class="ch c-flow">{esc(c["service"])}</span> : {esc(tr(c["desc"]).split(". ")[0])}'
                     f'<div class="lgl">{" · ".join(esc(x) for x in card_lines_cache[c["id"]])}</div>'
                     f'<div class="lgr">{"".join(f"<span><b>{esc(col)}</b> ← {esc(txt)}</span>" for col, txt in rules)}</div></li>')
    story.append("</ol>")
    return "".join(out), "".join(story)


STYLE = """
.lgh{font-size:13px;margin:14px 0 6px;color:#8b98a8;text-transform:uppercase;letter-spacing:.6px} .lgs{margin:0;padding-left:22px;font-size:13px} .lgs li{margin:0 0 10px}
.lgl{color:#8b98a8;font-size:12px;margin:2px 0} .lgr{display:flex;flex-wrap:wrap;gap:4px 14px;font-size:12px;color:#c9d1d9} .lgr b{color:#e6edf3;font-weight:600}
"""
SCRIPT = """<script>
(function(){const svg=document.querySelector('svg.lg');if(!svg)return;const lines=[...svg.querySelectorAll('.ln')],rows=[...svg.querySelectorAll('.row')];
function reset(){lines.forEach(l=>l.classList.remove('hi','dim'));rows.forEach(r=>r.classList.remove('hi'));}
function hiLines(pred){let any=false;lines.forEach(l=>{const on=pred(l);l.classList.toggle('hi',on);l.classList.toggle('dim',!on);if(on)any=true;});if(!any)reset();}
rows.forEach(r=>{r.addEventListener('mouseenter',()=>{const id=r.dataset.id;const tgt=new Set(),src=new Set();lines.forEach(l=>{if(l.dataset.t===id){tgt.add(l.dataset.t);if(l.dataset.s)src.add(l.dataset.s);}if(l.dataset.s===id)tgt.add(l.dataset.t);});
hiLines(l=>l.dataset.t===id||l.dataset.s===id||(tgt.has(l.dataset.t)&&(l.dataset.s===id||l.dataset.s==='')&&src.size>0&&tgt.has(id)));rows.forEach(x=>x.classList.toggle('hi',src.has(x.dataset.id)||tgt.has(x.dataset.id)));});r.addEventListener('mouseleave',reset);});
svg.querySelectorAll('.card').forEach(c=>{c.addEventListener('mouseenter',()=>hiLines(l=>l.dataset.card===c.dataset.card));c.addEventListener('mouseleave',reset);});})();
</script>"""
